# plugins:
# git - look at the latest commit on the branch and find a tag with the commit
# semver - grab the latest semver from the container registry
containers:
  bitwarden-secrets-operator:
    container: ghcr.io/jrcichra/bitwarden-secrets-operator
    plugin: git
    options:
      url: https://github.com/jrcichra/bitwarden-secrets-operator.git
      branch: master
  busybox:
    container: docker.io/library/busybox
    plugin: semver
# output types
# git - write the YAML to a file in a git repo
# file - write the YAML to a file
output:
  plugin: file
  options:
    name: "output.yaml"
